- hosts: all
  become: yes
  roles:
    - role: docker-monerod
      tags: docker-monerod
    - role: exporter/monerod
      tags: exporter/monerod
    - role: docker-monerod-keepalived
      tags: docker-monerod-keepalived
