- name: git clone files
  git:
    repo: https://github.com/fkshom/monerod-exporter
    dest: /tmp/monerod-exporter
  delegate_to: localhost

- name: copy files
  copy:
    src: /tmp/monerod-exporter
    dest: /home/user/

- name: docker-compose up -d
  docker_service:
    project_src: /home/user/monerod-exporter
    build: yes
    restarted: yes

- name: iptables
  iptables:
    chain: INPUT
    protocol: tcp
    match: tcp
    destination_port: "18083"
    jump: ACCEPT
