- name: git clone files
  git:
    src: https://github.com/fkshom/monerod-exporter
    dst: /tmp/monerod-exporter
  delegate-to: localhost

- name: copy files
  copy:
    src: /tmp/monerod-exporter
    dest: /home/monero/monerod-exporter

- name: docker-compose up -d
  docker_compose:
    project_src: /home/monero/monerod-exporter
    build: yes
    restarted: yes

- name: iptables
  iptables:
    chain: INPUT
    protocol: tcp
    match: tcp
    destination_port: 18083
    jump: ACCEPT
