# - name: install docker-compose py
#   pip:
#     name: docker-compose

- name: git clone files
  git:
    repo: https://github.com/fkshom/docker-monerod
    dest: /tmp/docker-monerod
  delegate_to: localhost

- name: copy files
  copy:
    src: /tmp/docker-monerod
    dest: /home/user/

- name: create volume directory
  file:
    path: /home/user/docker-monerod/volumes
    state: directory
    owner: 1000
    group: 1000
    mode: 0755
    recurse: yes

- name: docker-compose up -d
  docker_compose:
    project_src: /home/user/docker-monerod
    build: yes
    restarted: yes

- name: iptables
  iptables:
    chain: INPUT
    protocol: tcp
    match: tcp
    destination_port: "18089"
    jump: ACCEPT
