- name: Install keepalived
  package:
    name: keepalived
    state: latest
  tags: keepalived
  notify: restart keepalived

- name: Install check script
  template:
    src: "templates/check_script.sh.j2"
    dest: "/etc/keepalived/check_script.sh"
    mode: 0755
    owner: root
    group: root
  tags: keepalived
  notify: restart keepalived

- name: Keepalived configuration
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
  tags: keepalived
  notify: restart keepalived

- name: Start keepalived
  service:
    name: keepalived
    state: started
    enabled: yes
  tags: keepalived